version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network
    restart: always

networks:
  frontend-network:
    driver: bridge
