name: JavaScript CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The runner environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (specify the version in 'node-version')
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Replace with the version of Node.js you need

      # Step 3: Install dependencies (using npm install)
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test
        continue-on-error: false  # Fail the workflow if tests fail

      # Step 5: Build the project (if applicable)
      - name: Build project
        run: npm run build  # Use this if you have a build script in your package.json

      # Step 6: Deploy (optional step, only if you are deploying after a successful build)
      # For example, deploying to Netlify, Vercel, or any other hosting provider
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 18.175.138.249  # Server IP address
          username: ubuntu  # SSH username (e.g., deploy_user)
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}  # SSH private key for authentication
          port: 22  # Default SSH port
          script: |
            cd /home/ubuntu/PrimeAcademy
            git pull origin main  # Pull the latest code from the repository
            npm install  # Install dependencies on the server
            npm run build  # Run the build command if necessary
            pm2 restart app  # Restart the app using PM2 or your process manager
